### ISSUE TITLE
Add GPO changes to report

### ISSUE THREAD

**Issue by skest3qc** [Raj-GT/Windows-GroupPolicy-Monitor#1]
Would it be possible to add changes of the GPO to the report too?

**Comment by Raj-GT** [comment]
Thanks for your comment and I hope you find the script useful. The main purpose of the script is to simply notify a group/users of any GPO changes whilst automating the backup process. While an option of change reporting would be useful (and something I was experimenting with) I couldn't find an HTML diff tool that would produce a usable report. I might give it another go when I come across a library that produces nicely formatted HTML.
